FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

RUN yarn

# Bundle app source
COPY . .
# set to production
COPY .env.production .env

RUN yarn build

# ENV Vars
ENV NODE_ENV production

# PORT
EXPOSE 8080
# COMMAND TO RUN APP
CMD [ "node", "dist/index.js" ]
USER node